#!/bin/bash
# Byeori Project Creator
# Usage: ./create-project.sh <project-name> [description]

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
TEMPLATE_DIR="$REPO_ROOT/templates/project-skeleton"
PROJECTS_DIR="$REPO_ROOT/Projects"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
print_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_info() {
    echo -e "${YELLOW}[INFO]${NC} $1"
}

usage() {
    echo "Usage: $0 <project-name> [description]"
    echo ""
    echo "Arguments:"
    echo "  project-name    Name of the project (required, no spaces)"
    echo "  description     Project description (optional)"
    echo ""
    echo "Example:"
    echo "  $0 my-awesome-app \"An awesome application\""
    exit 1
}

# Validation
if [ -z "$1" ]; then
    print_error "Project name is required"
    usage
fi

PROJECT_NAME="$1"
PROJECT_DESC="${2:-No description provided}"

# Validate project name (alphanumeric, hyphens, underscores only)
if [[ ! "$PROJECT_NAME" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
    print_error "Invalid project name. Use only letters, numbers, hyphens, and underscores. Must start with a letter."
    exit 1
fi

TARGET_DIR="$PROJECTS_DIR/$PROJECT_NAME"

# Check if project already exists
if [ -d "$TARGET_DIR" ]; then
    print_error "Project '$PROJECT_NAME' already exists at $TARGET_DIR"
    exit 1
fi

# Check if template exists
if [ ! -d "$TEMPLATE_DIR" ]; then
    print_error "Template directory not found: $TEMPLATE_DIR"
    exit 1
fi

# Create project
print_info "Creating project: $PROJECT_NAME"

# Copy template
cp -r "$TEMPLATE_DIR" "$TARGET_DIR"
print_info "Copied template structure"

# Create project metadata
CREATED_DATE=$(date +%Y-%m-%d)
META_FILE="$TARGET_DIR/00_context/project-meta.md"

cat > "$META_FILE" << EOF
# Project Metadata

## Basic Information

| Field | Value |
|-------|-------|
| **Project Name** | $PROJECT_NAME |
| **Description** | $PROJECT_DESC |
| **Created** | $CREATED_DATE |
| **Current Version** | v0.1 |
| **Status** | Draft |

---

## Version History

| Version | Date | Description |
|---------|------|-------------|
| v0.1 | $CREATED_DATE | Initial project creation |

---

## Notes

- This file is auto-generated by Byeori project creator
- Update version when creating snapshots in \`40_versions/\`
EOF

print_info "Created project metadata"

# Summary
print_success "Project '$PROJECT_NAME' created successfully!"
echo ""
echo "Location: $TARGET_DIR"
echo ""
echo "Next steps:"
echo "  1. Add context materials to: $TARGET_DIR/00_context/"
echo "  2. Invoke @product-prd to start PRD generation"
echo ""
