# Byeori Project Creator (PowerShell)
# Usage: .\create-project.ps1 -ProjectName <name> [-Description <desc>]

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true, Position=0)]
    [ValidatePattern('^[a-zA-Z][a-zA-Z0-9_-]*$')]
    [string]$ProjectName,

    [Parameter(Mandatory=$false, Position=1)]
    [string]$Description = "No description provided"
)

# Configuration
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$TemplateDir = Join-Path $RepoRoot "templates\project-skeleton"
$ProjectsDir = Join-Path $RepoRoot "Projects"

# Functions
function Write-Error-Message {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

function Write-Success {
    param([string]$Message)
    Write-Host "[SUCCESS] $Message" -ForegroundColor Green
}

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Yellow
}

# Validation
$TargetDir = Join-Path $ProjectsDir $ProjectName

# Check if project already exists
if (Test-Path $TargetDir) {
    Write-Error-Message "Project '$ProjectName' already exists at $TargetDir"
    exit 1
}

# Check if template exists
if (-not (Test-Path $TemplateDir)) {
    Write-Error-Message "Template directory not found: $TemplateDir"
    exit 1
}

# Create project
Write-Info "Creating project: $ProjectName"

# Copy template
Copy-Item -Path $TemplateDir -Destination $TargetDir -Recurse
Write-Info "Copied template structure"

# Create project metadata
$CreatedDate = Get-Date -Format "yyyy-MM-dd"
$MetaFile = Join-Path $TargetDir "00_context\project-meta.md"

$MetaContent = @"
# Project Metadata

## Basic Information

| Field | Value |
|-------|-------|
| **Project Name** | $ProjectName |
| **Description** | $Description |
| **Created** | $CreatedDate |
| **Current Version** | v0.1 |
| **Status** | Draft |

---

## Version History

| Version | Date | Description |
|---------|------|-------------|
| v0.1 | $CreatedDate | Initial project creation |

---

## Notes

- This file is auto-generated by Byeori project creator
- Update version when creating snapshots in ``40_versions/``
"@

# Ensure directory exists
$MetaDir = Split-Path -Parent $MetaFile
if (-not (Test-Path $MetaDir)) {
    New-Item -ItemType Directory -Path $MetaDir -Force | Out-Null
}

Set-Content -Path $MetaFile -Value $MetaContent -Encoding UTF8
Write-Info "Created project metadata"

# Summary
Write-Success "Project '$ProjectName' created successfully!"
Write-Host ""
Write-Host "Location: $TargetDir"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Add context materials to: $TargetDir\00_context\"
Write-Host "  2. Invoke @product-prd to start PRD generation"
Write-Host ""
